version: '3.7'

services:
  stickynotes:
    build: .

    command: python /stickynotes/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/stickynotes
    ports:
      - 5000:8000
    depends_on:
      - db
    networks:
      - testenvnet

  db:
    image: postgres:13
    ports:
      - 5438:5432
    environment:
      - POSTGRESQL_ADMIN_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/:rw
    networks:
      - testenvnet

      
networks:
    testenvnet:
        driver: "bridge"
volumes: 
    .:
        name: .

volumes: 
    postgres_data:
        name: postgres_data